# First, build the application in the `/app` directory.
# See `Dockerfile` for details.
FROM ghcr.io/astral-sh/uv:python3.14-alpine AS builder
ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy

# Disable Python downloads, because we want to use the system interpreter
# across both images. If using a managed Python version, it needs to be
# copied from the build image into the final image; see `standalone.Dockerfile`
# for an example.
ENV UV_PYTHON_DOWNLOADS=0


WORKDIR /app
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --no-default-groups
COPY . /app
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-default-groups

# Remove the python build folder
RUN rm -rf /app/build

# Remove the .egg-info file that are created from setuptools
RUN find /app -type d -name '*.egg-info' -exec rm -rf {} +

# Then, use a final image without uv
FROM python:3.14-alpine
# It is important to use the image that matches the builder, as the path to the
# Python executable must be the same, e.g., using `python:3.11-slim-bookworm`
# will fail.

## Create a non-root user and group for running the application
RUN addgroup -S chithi \
    && adduser -S -G chithi -h /app -s /bin/sh chithi

# Copy the application from the builder and make it owned by the chithi user
COPY --from=builder --chown=chithi:chithi /app /app

# Place executables in the environment at the front of the path
ENV PATH="/app/.venv/bin:$PATH"

ENV HOST=127.0.0.1
ENV PORT=8000
EXPOSE 8000/udp 8000/tcp

# Use a non-root user
WORKDIR /app
USER chithi

