/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FuckRouteImport } from './routes/fuck'
import { Route as IndexRouteImport } from './routes/index'

const FuckRoute = FuckRouteImport.update({
  id: '/fuck',
  path: '/fuck',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fuck': typeof FuckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fuck': typeof FuckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fuck': typeof FuckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fuck'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fuck'
  id: '__root__' | '/' | '/fuck'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FuckRoute: typeof FuckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fuck': {
      id: '/fuck'
      path: '/fuck'
      fullPath: '/fuck'
      preLoaderRoute: typeof FuckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FuckRoute: FuckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
