"""make number_of_files nullable

Revision ID: 9bdf8ded6482
Revises: bac557cb9bc0
Create Date: 2026-05-15 18:33:54.953211

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9bdf8ded6482"
down_revision: str | Sequence[str] | None = "bac557cb9bc0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("number_of_files", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "number_of_files")
    # ### end Alembic commands ###
