"""Addinstance down row

Revision ID: bac557cb9bc0
Revises: d228bf522042
Create Date: 2026-04-25 12:34:48.026083

"""

from typing import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "bac557cb9bc0"
down_revision: str | Sequence[str] | None = "d228bf522042"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "config",
        sa.Column(
            "allow_uploads",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("config", "allow_uploads")
    # ### end Alembic commands ###
